apiVersion: v1
kind: Service
metadata:
  name: {{.Values.configsServiceName}}
  namespace: {{.Values.swaggerhubNamespace}}
  labels:
    app: {{.Values.coreApp}}
spec:
  type: {{.Values.swaggerhubServiceType}}
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: {{.Values.configsNodePort}}
  selector:
    app: {{.Values.coreApp}}
    tier: {{.Values.configsTier}}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{.Values.configsTier}}
  namespace: {{.Values.swaggerhubNamespace}}
  labels:
    app: {{.Values.coreApp}}
spec:
  replicas: {{.Values.configsReplicas}}
  selector:
    matchLabels:
      app: {{.Values.coreApp}}
      tier: {{.Values.configsTier}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.coreApp}}
        tier: {{.Values.configsTier}}
    spec:
      containers:
      - image: {{.Values.registry}}smartbear/swaggerhub-configs-service:{{.Values.configsTag}}
        name: {{.Values.configsTier}}
        env:
        - name: configs-service.mongo.uri
          value: {{.Values.mongoURI}}
        - name: ENABLE_HTTP
          value: "true"
        - name: ENABLE_HTTPS
          value: "false"
        - name: SAAS
          value: "true"
        - name: configs-service.mongo.db
          value: "configs"
        - name: configs-service.refreshInterval
          value: "60"
        ports:
        - containerPort: 8000
          name: {{.Values.configsTier}}
      nodeSelector:
        core: "true" 
